add ui test popup

diff --git a/.github/workflows/xcode-build.yml b/.github/workflows/xcode-build.yml
--- a/.github/workflows/xcode-build.yml
+++ b/.github/workflows/xcode-build.yml
@@ -31,8 +31,16 @@ jobs:
           -scheme SlimHUD-GitHub-Action \
           -destination platform=macOS \
           -resultBundlePath TestResults \
-          -test-iterations 7 -retry-tests-on-failure \
+          -test-iterations 20 -retry-tests-on-failure \
           CODE_SIGNING_ALLOWED=NO || exit 1
+      - name: Post test results
+        uses: kishikawakatsumi/xcresulttool@v1.7.1
+        if: ${{ (success() || failure()) && github.event_name == 'pull_request' }}
+        with:
+          path: "TestResults.xcresult"
+          title: ${{ env.test-results-check-name }}
+          upload-bundles: never
+          show-code-coverage: true
       - name: Generate coverage report
         run: |
           bash ./Configuration/xccov-to-sonarqube-generic.sh TestResults.xcresult/ > sonarqube-generic-coverage.xml
@@ -58,8 +66,7 @@ jobs:
         run: |
           sonar-scanner
       - name: Check failures
-        # Flaky tests make the output status generated by kishikawakatsumi/xcresulttool not reliable. Using xcodebuild's status directly.
-        #  This means that this workflow could and will fail if some test don't pass, even after retrying.
-        #  As the additional MR check generated by xcresulttool would fail for those flaky tests, it would only be confusing - therefore removing it entirely
+        # Flaky tests make the output status generated by xcresulttool not reliable. Using xcodebuild's status directly.
+        # This means that this workflow could and will fail if some test don't pass, even after retrying them
         if: steps.run-tests.outcome != 'success'
         run: exit 1
