handle flaky tests
update ui tests

test flaky tests


test flaky tests


remove kishikawakatsumi/xcresulttool


re-add ui tests

diff --git a/.github/workflows/xcode-build.yml b/.github/workflows/xcode-build.yml
--- a/.github/workflows/xcode-build.yml
+++ b/.github/workflows/xcode-build.yml
@@ -22,27 +22,17 @@ jobs:
 
       - name: Switch Xcode version
         run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
-      - name: Xcode version
-        run: /usr/bin/xcodebuild -version
-
       - name: Build and Test
         continue-on-error: true
+        id: run-tests
         run: |
           xcodebuild clean test \
           -project SlimHUD.xcodeproj \
           -scheme SlimHUD-GitHub-Action \
           -destination platform=macOS \
           -resultBundlePath TestResults \
-          -test-iterations 30 -retry-tests-on-failure \
-          CODE_SIGNING_ALLOWED=NO
-      - name: Post test results
-        uses: kishikawakatsumi/xcresulttool@v1.7.1
-        if: ${{ (success() || failure()) && github.event_name == 'pull_request' }}
-        with:
-          path: "TestResults.xcresult"
-          title: ${{ env.test-results-check-name }}
-          upload-bundles: never
-          show-code-coverage: true
+          -test-iterations 7 -retry-tests-on-failure \
+          CODE_SIGNING_ALLOWED=NO || exit 1
       - name: Generate coverage report
         run: |
           bash ./Configuration/xccov-to-sonarqube-generic.sh TestResults.xcresult/ > sonarqube-generic-coverage.xml
@@ -67,3 +57,9 @@ jobs:
       - name: Run sonarqube
         run: |
           sonar-scanner
+      - name: Check failures
+        # Flaky tests make the output status generated by kishikawakatsumi/xcresulttool not reliable. Using xcodebuild's status directly.
+        #  This means that this workflow could and will fail if some test don't pass, even after retrying.
+        #  As the additional MR check generated by xcresulttool would fail for those flaky tests, it would only be confusing - therefore removing it entirely
+        if: steps.run-tests.outcome != 'success'
+        run: exit 1
